// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdNrIBX7-rTzS5daivCFfHGpz4AwO2h9A',
    appId: '1:255379998805:web:7df319cd99ce026c242cdc',
    messagingSenderId: '255379998805',
    projectId: 'islami-31dfd',
    authDomain: 'islami-31dfd.firebaseapp.com',
    storageBucket: 'islami-31dfd.firebasestorage.app',
    measurementId: 'G-2THC9FG797',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv3Itbsiwl8cKw8ufuW2zKFwgQ2VeI9_E',
    appId: '1:255379998805:android:a4b55d8b14e7af87242cdc',
    messagingSenderId: '255379998805',
    projectId: 'islami-31dfd',
    storageBucket: 'islami-31dfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADVAdnIgHoajEf5PDGR--L4SV1mcxzljA',
    appId: '1:255379998805:ios:ce8b0d3031849921242cdc',
    messagingSenderId: '255379998805',
    projectId: 'islami-31dfd',
    storageBucket: 'islami-31dfd.firebasestorage.app',
    iosBundleId: 'com.example.islami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADVAdnIgHoajEf5PDGR--L4SV1mcxzljA',
    appId: '1:255379998805:ios:ce8b0d3031849921242cdc',
    messagingSenderId: '255379998805',
    projectId: 'islami-31dfd',
    storageBucket: 'islami-31dfd.firebasestorage.app',
    iosBundleId: 'com.example.islami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdNrIBX7-rTzS5daivCFfHGpz4AwO2h9A',
    appId: '1:255379998805:web:e18afa2afcb69ee1242cdc',
    messagingSenderId: '255379998805',
    projectId: 'islami-31dfd',
    authDomain: 'islami-31dfd.firebaseapp.com',
    storageBucket: 'islami-31dfd.firebasestorage.app',
    measurementId: 'G-902MGZCHN2',
  );

}